<a href="https://colab.research.google.com/github/basia1809/data-science-bootcamp/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##**Podstawy**

# Nowa sekcja

# Nowa sekcja

Import biblioteki i wersja


In [ ]:
import numpy as np
np.__version__

'1.23.5'

Atrybuty biblioteki

In [ ]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_CopyMode', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__getattr__', '__git_version__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_distributor_in

Tworzenie tablic pomoc


In [ ]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', '

 **Tablice 1 wymiarowe**


In [ ]:
x= np.array([1,3])
x

array([1, 3])

In [ ]:
print(x)

[1 3]


In [ ]:
type(x)

numpy.ndarray

In [ ]:
x.ndim

1

In [ ]:
x.shape

(2,)

In [ ]:
x.size

2

In [ ]:
x.dtype

dtype('int64')

In [ ]:
x=np.array([1.3,2.3,1.4])
print(x)

[1.3 2.3 1.4]


In [ ]:
x.dtype

dtype('float64')

** Tablice 2 wymiorowe**

In [ ]:
x=np.array([[1,2], [-3,1]])
x

array([[ 1,  2],
       [-3,  1]])

In [ ]:
x.ndim

2

In [ ]:
x.shape

(2, 2)

In [ ]:
x=np.array([[1,2,4],[4,2,1]])
print(x)

[[1 2 4]
 [4 2 1]]


In [ ]:
x.shape

(2, 3)

**Tablice 3 wymiarowe**

In [ ]:
x=np.array(
    [[[4,3,1],
     [3,1,2]],
     [[4,1,3],
      [4,2,1]]])
x

array([[[4, 3, 1],
        [3, 1, 2]],

       [[4, 1, 3],
        [4, 2, 1]]])

In [ ]:
x.ndim

3

In [ ]:
x.shape

(2, 2, 3)

# **Typy danych**

In [ ]:
A=np.array([1,2,3])
A.dtype

dtype('int64')

In [ ]:
A=np.array([1.0,2,3])
A.dtype

dtype('float64')

In [ ]:
A=np.array([1,2,3],dtype='float')
A.dtype

dtype('float64')

In [ ]:
A=np.array([1,2,3],dtype='complex')
A.dtype

dtype('complex128')

In [ ]:
A=np.array([1.1,2.7,3],dtype='int')
A.dtype

dtype('int64')

In [ ]:
print(A)

[1 2 3]


In [ ]:
A=np.array([True,False])
A.dtype

dtype('bool')

In [ ]:
A=np.array([24,120,500],dtype=np.int8)
A.dtype


dtype('int8')

In [ ]:
print(A)

[ 24 120 -12]


In [ ]:
A=np.array([24,120,230],dtype=np.uint8)
A.dtype

dtype('uint8')

## **Tworzenie tablic**

In [ ]:
np.zeros(shape=(4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
np.zeros(shape=(4,10),dtype='int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
np.ones(shape=(5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.ones(shape=(5,5),dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
np.full(shape=(3,3),fill_value=4,dtype='int')

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(start=5,stop=10)

array([5, 6, 7, 8, 9])

In [ ]:
np.arange(start=10,stop=100,step=10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
np.arange(start=100,stop=10,step=-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [ ]:
np.arange(start=0,stop=1,step=0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [ ]:
np.linspace(start=0,stop=1,num=11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [ ]:
A=np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
A.reshape((3,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

Zmiana kształtu z automatycznie dobraną liczbą wierszy

In [ ]:
A.reshape((3,-1))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

i kolumn

In [ ]:
A.reshape((-1,3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

# **Podstawowe operacje na tablicach**

In [ ]:
A=np.array([3,1,4,2])
B=np.array([3,-1,3,2])
print(A)
print(B)

[3 1 4 2]
[ 3 -1  3  2]


In [ ]:
A+B


array([6, 0, 7, 4])

In [ ]:
np.add(A,B)

array([6, 0, 7, 4])

In [ ]:
A-B

array([0, 2, 1, 0])

In [ ]:
np.subtract(A,B)

array([0, 2, 1, 0])

In [ ]:
A*B

array([ 9, -1, 12,  4])

In [ ]:
np.multiply(A,B)

array([ 9, -1, 12,  4])

In [ ]:
A/B

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [ ]:
np.divide(A,B)

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [ ]:
A+3

array([6, 4, 7, 5])

In [ ]:
A*2

array([6, 2, 8, 4])

Mnożenie macierzowe

In [ ]:
X=np.array([[1,3],[-2,0]])
Y=np.array([[6,0],[-1,2]])
print(X,'\n')
print(Y)

[[ 1  3]
 [-2  0]] 

[[ 6  0]
 [-1  2]]


In [ ]:
X*Y

array([[6, 0],
       [2, 0]])

In [ ]:
np.dot(X,Y)

array([[  3,   6],
       [-12,   0]])

In [ ]:
X.dot(Y)

array([[  3,   6],
       [-12,   0]])

In [ ]:
X@Y

array([[  3,   6],
       [-12,   0]])

# **Losowanie liczb pseudolosowych**

In [ ]:
np.random.seed(0)

In [ ]:
np.random.rand(10)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ,
       0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152])

In [ ]:
np.random.rand()

0.7917250380826646

In [ ]:
np.random.rand(10)

array([0.52889492, 0.56804456, 0.92559664, 0.07103606, 0.0871293 ,
       0.0202184 , 0.83261985, 0.77815675, 0.87001215, 0.97861834])

In [ ]:
np.random.rand(10,2)

array([[0.79915856, 0.46147936],
       [0.78052918, 0.11827443],
       [0.63992102, 0.14335329],
       [0.94466892, 0.52184832],
       [0.41466194, 0.26455561],
       [0.77423369, 0.45615033],
       [0.56843395, 0.0187898 ],
       [0.6176355 , 0.61209572],
       [0.616934  , 0.94374808],
       [0.6818203 , 0.3595079 ]])

In [ ]:
np.random.randint(10)

8

In [ ]:
np.random.randint(low=10,high=101)

11

In [ ]:
np.random.randint(low=10,high=101,size=10)

array([75, 51, 67, 45, 21, 56, 92, 10, 24, 63])

In [ ]:
np.random.choice([4,5,6])

4

In [ ]:
np.random.choice(['python','java','sql'])

'java'

In [ ]:
data=np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.random.shuffle(data)

In [ ]:
data

array([1, 2, 5, 0, 3, 7, 8, 6, 9, 4])

# **Podstawowe funkcje**

In [ ]:
np.exp(1)

2.718281828459045

In [ ]:
np.sqrt(9)

3.0

Bada czy każda wartość zwraca True

In [ ]:
np.all([2,3,1])

True

In [ ]:
np.any([0,0,0])

False

In [ ]:
bool(2)

True

In [ ]:
A=np.random.rand(5)
A

array([0.2532916 , 0.46631077, 0.24442559, 0.15896958, 0.11037514])

In [ ]:
np.argmax(A)

1

In [ ]:
A[np.argmax(A)]

0.4663107728563063

In [ ]:
A[np.argmin(A)]

0.11037514116430513

In [ ]:
np.argsort(A)

array([4, 3, 2, 0, 1])

In [ ]:
np.max(A)

0.4663107728563063

In [ ]:
np.min(A)

0.11037514116430513

In [ ]:
np.mean(A)

0.24667453844150317

In [ ]:
np.median(A)

0.24442559200160274

In [ ]:
np.std(A)

0.12211355662593533

In [ ]:
np.max

<function numpy.amax(a, axis=None, out=None, keepdims=<no value>, initial=<no value>, where=<no value>)>

In [ ]:
B=np.array([1,2,3,3,4,4])
B

array([1, 2, 3, 3, 4, 4])

In [ ]:
np.argsort(B)

array([0, 1, 2, 3, 4, 5])

# Indeksowanie wycinanie

In [ ]:
import numpy as np
A =np.arange(20)

In [ ]:
A[2]

2

In [ ]:
A[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [ ]:
A[:2]

array([0, 1])

In [ ]:
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
A[10:15]

array([10, 11, 12, 13, 14])

In [ ]:
A=A.reshape(4,5)

In [ ]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
A[0]

array([0, 1, 2, 3, 4])

In [ ]:
A[:,0]

array([ 0,  5, 10, 15])

In [ ]:
A[-2]

array([10, 11, 12, 13, 14])

# Iteracja po tablicy


In [ ]:
A


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
for row in A:
  print(row)

[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]
[15 16 17 18 19]


In [ ]:
for row in A:
  print(row[:3])

[0 1 2]
[5 6 7]
[10 11 12]
[15 16 17]


In [ ]:
for row in A.flat:
  print(row)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [ ]:
A.ravel()



array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
A.T


array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

# Maski logiczne

In [ ]:
A=np.arange(start=-10,stop=10,step=0.5)
A=A.reshape(10,-1)
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [ ]:
A>0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
A[np.bitwise_and(A>-5,A<5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [ ]:
np.bitwise_or(A<-5,A>5)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])